# Generated by Django 4.0.4 on 2022-04-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('poster', models.FileField(upload_to='posters/')),
                ('release_year', models.PositiveIntegerField()),
                ('rotten_rate', models.PositiveIntegerField(max_length=100)),
                ('imdb_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
    ]
