# Generated by Django 4.0.4 on 2022-04-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_year',
            new_name='released_year',
        ),
        migrations.AlterField(
            model_name='movie',
            name='rotten_rate',
            field=models.PositiveIntegerField(),
        ),
    ]
