# Generated by Django 4.0.4 on 2022-04-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=models.CharField(choices=[('f', 'featured'), ('n', 'new')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='movies/posters/'),
        ),
    ]
