# Generated by Django 4.0.4 on 2022-04-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_tag_movie_trailer_alter_movie_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.FileField(null=True, upload_to='movies/trailers/'),
        ),
    ]
