# Generated by Django 4.0.4 on 2022-04-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(default='.', max_length=255),
            preserve_default=False,
        ),
    ]
