# Generated by Django 4.0.4 on 2022-04-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_review_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
